name: GitHub metrics
on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:

      - name: Personal metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, activity, community, repositories, metadata"
          plugin_habits: yes
          plugin_habits_from: 300
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugins_errors_fatal: yes
          config_timezone: Asia/Shanghai


